@REM This batch file has been generated by the IAR Embedded Workbench
@REM C-SPY Debugger, as an aid to preparing a command line for running
@REM the cspybat command line utility using the appropriate settings.
@REM
@REM You can launch cspybat by typing the name of this batch file followed
@REM by the name of the debug file (usually an ELF/DWARF or UBROF file).
@REM Note that this file is generated every time a new debug session
@REM is initialized, so you may want to move or rename the file before
@REM making changes.
@REM 


"G:\Peleus_Program Files\IAR for ARM\common\bin\cspybat" "G:\Peleus_Program Files\IAR for ARM\arm\bin\armproc.dll" "G:\Peleus_Program Files\IAR for ARM\arm\bin\armjlink.dll"  %1 --plugin "G:\Peleus_Program Files\IAR for ARM\arm\bin\armbat.dll" --flash_loader "G:\Peleus_Program Files\IAR for ARM\arm\config\flashloader\ST\FlashSTM32W108.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--jlink_exec_command" "SetSysPowerDownOnIdle = 50; SetDbgPowerDownOnClose = 1" "--fpu=None" "-p" "F:\Project-related\STM32W108\myCode\实验4 16点组网\工程源代码\simplemac\demos\sample/../../../hal/micro/cortexm3/stm32w108/regs.ddf" "--drv_verify_download" "--semihosting=none" "--device=STM32W108" "--drv_communication=USB0" "--jlink_speed=auto" "--jlink_initial_speed=32" "--jlink_reset_strategy=0,0" "--jlink_interface=SWD" "--drv_catch_exceptions=0x000" 


